# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [51]:
# Import NumPy as its abbreviation 'np'
import numpy as np

# Check the version
print(np.__version__)


2.2.1


In [52]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])



Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [53]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)


((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [55]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)


((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [56]:
# Attributes of 3-dimensional array

a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [57]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

# Create a DataFrame from the 2-dimensional array (a2)
df = pd.DataFrame(a2)
print(df)



     0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5


In [58]:
# Create an array of shape (10, 2) with only ones
import numpy as np

ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [74]:
# Create an array of shape (7, 2, 3) of only zeros


zeros = np.zeros((7, 2, 3))
zeros



array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [75]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array



array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [76]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array



array([[9, 5],
       [9, 9],
       [5, 0],
       [3, 9],
       [5, 5],
       [4, 0],
       [7, 4]], dtype=int32)

In [73]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 5))


array([[0.25620694, 0.61151371, 0.08159418, 0.00518486, 0.62789441],
       [0.19427395, 0.07094092, 0.39678383, 0.05076853, 0.88661715],
       [0.02761677, 0.5788649 , 0.43847412, 0.67202614, 0.32815267]])

In [80]:
# Set the random seed to 42


# Create a random array of numbers between 0 & 10 of size (4, 6)

np.random.seed(42)
# Make 'random' numbers
np.random.randint(10, size=(4, 6))


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?
the number are same 

In [93]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable


random_array = np.random.randint( 10, size=(3, 7))

# Find the unique numbers in the array
unique_numbers = np.unique(random_array)
print(unique_numbers)


[0 2 3 4 5 6 7 8 9]


In [132]:
# Find the 0'th index of the latest array you created

random_array[0]



array([2, 7, 5, 2, 0, 2, 4], dtype=int32)

In [133]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[2, 7, 5, 2, 0, 2, 4],
       [2, 0, 4, 9, 6, 6, 8]], dtype=int32)

In [134]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]


array([[2, 7],
       [2, 0]], dtype=int32)

In [141]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_array = np.random.randint(0, 10, size=(3, 5))
ones_array = np.ones((3, 5))
print(random_array, ones_array)

[[8 6 0 0 8]
 [8 3 8 2 6]
 [5 7 8 4 0]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [142]:
# Add the two arrays together
result = random_array + ones_array
print(result)


[[9. 7. 1. 1. 9.]
 [9. 4. 9. 3. 7.]
 [6. 8. 9. 5. 1.]]


In [143]:
# Create another array of ones of shape (5, 3)
ones_array_2 = np.ones((5, 3))
print(ones_array_2)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [170]:
# Try add the array of ones and the other most recent array together
# Attempt to add the two arrays of different shapes
result = ones_array + ones_array_2.T
print(result)



[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [146]:
# Create another array of ones of shape (3, 5)
ones_array_3 = np.ones((3, 5))
print(ones_array_3)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [169]:
# Subtract the new array of ones from the other most recent array
result = ones_array_3 - ones_array_2.T
print( result)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [171]:
# Multiply the ones array with the latest array
result = ones_array_3 * ones_array_2.T
print( result)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [151]:
# Take the latest array to the power of 2 using '**'
result = ones_array_3 ** 2
print( result)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [152]:
# Do the same thing with np.square()
result = np.square(ones_array_3)
print( result)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [153]:
# Find the mean of the latest array using np.mean()
mean_value = np.mean(ones_array_3)
print( mean_value)


1.0


In [154]:
# Find the maximum of the latest array using np.max()
max_value = np.max(ones_array_3)
print( max_value)


1.0


In [155]:
# Find the minimum of the latest array using np.min()
min_value = np.min(ones_array_3)
print( min_value)


1.0


In [158]:
# Find the standard deviation of the latest array
std_dev = np.std(ones_array_3)
print( std_dev)


0.0


In [159]:
# Find the variance of the latest array
variance = np.var(ones_array_3)
print( variance)


0.0


In [160]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = ones_array_3.reshape(3, 5, 1)
print( reshaped_array)


[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [161]:
# Transpose the latest array
transposed = reshaped_array.transpose()
print( transposed)


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


What does the transpose do?

In [162]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_1 = np.random.randint(0, 10, size=(3, 3))
array_2 = np.random.randint(0, 10, size=(3, 2))

print( array_1)
print( array_2)


[[2 9 7]
 [5 7 8]
 [3 0 0]]
[[9 3]
 [6 1]
 [2 0]]


In [163]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(array_1, array_2)
print( dot_product)


[[ 86  15]
 [103  22]
 [ 27   9]]


In [164]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_1 = np.random.randint(0, 10, size=(4, 3))
array_2 = np.random.randint(0, 10, size=(4, 3))

print( array_1)
print( array_2)


[[4 0 7]
 [0 0 1]
 [1 5 6]
 [4 0 0]]
[[2 1 4]
 [9 5 6]
 [3 6 7]
 [0 5 7]]


In [168]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(array_1, array_2.T)
print( dot_product)


[[36 78 61 49]
 [ 4  6  7  7]
 [31 70 75 67]
 [ 8 36 12  0]]


It doesn't work. How would you fix it?

In [173]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
transposed_array_2 = array_2.T
dot_product = np.dot(array_1, array_2.T)
print( dot_product)


[[36 78 61 49]
 [ 4  6  7  7]
 [31 70 75 67]
 [ 8 36 12  0]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [174]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_1 = np.random.randint(0, 10, size=(3, 3))
array_2 = np.random.randint(0, 10, size=(3, 3))

print( array_1)
print( array_2)


[[4 3 1]
 [5 5 0]
 [8 5 2]]
[[3 3 2]
 [9 2 2]
 [3 6 3]]


In [175]:
# Compare the two arrays with '>'
comparison_result = array_1 > array_2
print( comparison_result)


[[ True False False]
 [False  True False]
 [ True False False]]


What happens when you compare the arrays with `>`?

In [176]:
# Compare the two arrays with '>='
comparison_result = array_1 >= array_2
print( comparison_result)


[[ True  True False]
 [False  True False]
 [ True False False]]


In [177]:
# Find which elements of the first array are greater than 7
greater_than_7 = array_1 > 7
print( greater_than_7)


[[False False False]
 [False False False]
 [ True False False]]


In [178]:
# Which parts of each array are equal? (try using '==')
equal_elements = array_1 == array_2
print( equal_elements)


[[False  True False]
 [False False False]
 [False False False]]


In [180]:
# Sort one of the arrays you just created in ascending order
sorted_array = np.sort(array_1)
print( sorted_array)


[[1 3 4]
 [0 5 5]
 [2 5 8]]


In [181]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = np.argsort(array_1)
print( sorted_indexes)


[[2 1 0]
 [2 0 1]
 [2 1 0]]


In [182]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array_1)
print( max_index)


6


In [183]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(array_1)
print( min_index)


5


In [184]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indexes_axis_1 = np.argmax(array_1, axis=1)
print( max_indexes_axis_1)


[0 0 0]


In [189]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indexes_axis_0 = np.argmin(array_1, axis=0)
print( min_indexes_axis_0)


[0 0 1]


In [190]:
# Create an array of normally distributed random numbers
array = np.random.randn(2, 3)  
print( array)


[[-0.2854893   1.06529247  0.85399779]
 [ 1.78859386  0.56689407 -0.16450043]]


In [187]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array = np.linspace(1, 100, 10)
print( array)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.